ugosite/urls.py
from django.urls import path
from . import views

import youtube

urlpatterns = [
    path('', views.index, name='index'),
]

urlpatterns += [
    path('article/<int:pk>', views.ArticleDetailView.as_view(), name='article-detail'),
    path('articles/', views.ArticleListView.as_view(), name='articles'),
]

urlpatterns += [
    path('term/<int:pk>', views.TermDetailView.as_view(), name='term-detail'),
    path('terms/', views.TermListView.as_view(), name='terms'),
]

urlpatterns += [
    path('category/<int:pk>', views.CategoryDetailView.as_view(), name='category-detail'),
    path('categorys/', views.CategoryListView.as_view(), name='categorys'),
]

urlpatterns += [
    path('problem/<int:pk>', views.ProblemDetailView.as_view(), name='problem-detail'),
    path('problems/', views.ProblemListView.as_view(), name='problems'),
]

urlpatterns += [
    # path('randomvideo/', youtube.views.VideoOnAppListView.as_view(), name='random_video'),
    path('video_search/<int:pk>', youtube.views.VideoSearchView.as_view(), name='video_search'),
    path('video/<int:pk>', youtube.views.VideoOnAppDetailView.as_view(), name='video-detail'),
]

ugosuu/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add paths from the catalog application
from django.urls import include

urlpatterns += [
    path('ugosite/', include('ugosite.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='ugosite/', permanent=True)),
]

# Use static() to add URL mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

youtube/models.py
from django.db import models

# ユーティリティ
import util.normalize as normalize
import util.text_transform as text_transform

import sys

from apiclient.discovery import build

import httplib2,os

from google_auth_oauthlib.flow import InstalledAppFlow
from apiclient.discovery import build

import youtube.update as update
import youtube.download as download

# YOUTUBE_API_Key = 'AIzaSyD-ohN5V0dlXYHjP7lSrUgKcCgXDkjpR14'
YOUTUBE_API_KEY = 'AIzaSyCSZDXmnKDlNZMy8-P7EZOK44XmHWr9Y_w'


CLIENT_SECRETS_FILE = 'client_secret.json'

# This OAuth 2.0 access scope allows for full read/write access to the
# authenticated user's account.
SCOPES = ["https://www.googleapis.com/auth/youtube"]
YOUTUBE_API_SERVICE_NAME = 'youtube'
YOUTUBE_API_VERSION = 'v3'

import pickle
from google.auth.transport.requests import Request

from django.db import models

def get_authenticated_service():
    creds = None
    # The file token.pickle stores the user's access and refresh tokens, and is
    # created automatically when the authorization flow completes for the first
    # time.
    if os.path.exists('token.pickle'):
        with open('token.pickle', 'rb') as token:
            creds = pickle.load(token)
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                CLIENT_SECRETS_FILE, SCOPES)
            creds = flow.run_local_server(port=0)
        # Save the credentials for the next run
        with open('token.pickle', 'wb') as token:
            pickle.dump(creds, token)

    return build(YOUTUBE_API_SERVICE_NAME, YOUTUBE_API_VERSION, credentials=creds)

# youtube_with_auth = get_authenticated_service()
youtube_with_key = build('youtube', 'v3', developerKey=YOUTUBE_API_KEY)

import webbrowser


class Channel(models.Model):
    channelId = models.CharField(max_length=100,help_text='チャンネルのYoutubeIDを入力してください')

    def channel_sections(self):
        query_set = ChannelSection.objects.filter(data__snippet__channelId = self.channelId)
        return list(query_set)

    def download_sections(self):#,pagetoken)
        print("チャンネル「%s」のセクションをダウンロードします" % self.channelId)
        res = youtube_with_key.channelSections().list(
            channelId = self.channelId,
            part='snippet,contentDetails',
        ).execute()
        for data in res["items"]:
            if not data["snippet"]["type"] == "multipleplaylists" : continue
            new_section = ChannelSection.objects.create(data = data)
            print("ChannelSection「%s」を新たに追加しました。" % new_section)

    def download_playlists(self):#,pagetoken)
        print("チャンネル「%s」のプレイリストをダウンロードします" % self.channelId)
        pageToken = ""
        playlists = []
        while True:
            res = youtube_with_key.playlists().list(
                channelId = self.channelId,
                part='snippet',
                maxResults = 100,
                pageToken = pageToken
            ).execute() 
            playlists.extend(res["items"])
            try:
                pageToken = res["nextPageToken"]
                continue
            except:
                break
        for data in playlists:
            Playlist.objects.create(data = data)
    
    def download_uploads_playlistItems(self):
        print("Cannnel「%s」のアップロードプレイリストをダウンロードします" % self.channelId)
        res = youtube_with_key.channels().list(
            id = self.channelId,
            part="contentDetails"
        ).execute()
        channel_data = res["items"][0]
        print(channel_data)
        pageToken = ""
        playlistItems = []
        while True:
            print("チャンネル「%s」のアップロードプレイリストのページトークン「%s」をダウンロードします" % (self.channelId,pageToken))
            playlistItems_res = youtube_with_key.playlistItems().list(
                playlistId = channel_data["contentDetails"]["relatedPlaylists"]["uploads"],
                part='snippet',
                maxResults = 100,
                pageToken = pageToken
            ).execute()
            playlistItems.extend(playlistItems_res["items"])
            # if not playlistItems_res["nextPageToken"] : 
            try:
                pageToken = playlistItems_res["nextPageToken"]
                continue
            except:
                break
        
        return [PlaylistItem(data = data) for data in playlistItems]

class ChannelSection(models.Model):
    data = models.JSONField(help_text='このFieldはYoutubeAPIによって読み込まれます。')

    def title(self):
        return self.data["snippet"]["title"]

    def __str__(self):
        return self.title()

    def playlists(self):
        playlistIds = self.data["contentDetails"]["playlists"]
        playlists = []
        for playlistId in playlistIds:
            filtered_playlists = Playlist.objects.filter(data__id = playlistId)
            if len(filtered_playlists)>1:
                print("プレイリスト「%s」は複数存在します！" % filtered_playlists[0])
                sys.exit()
            if len(filtered_playlists)==0:
                print("プレイリスト「%s」は存在しません！" % playlistId)
                return []
            playlists.append(filtered_playlists[0])
        return playlists 
    
class Playlist(models.Model):
    data = models.JSONField(help_text='このFieldはYoutubeAPIによって読み込まれます。')

    def playlistId(self):
        return self.data["id"]

    def title(self):
        return self.data["snippet"]["title"]

    def description(self):
        return self.data["snippet"]["description"]
    
    def __str__(self):
        return self.title()
    
    def playlistItems(self):
        playlistId = self.playlistId()
        items = PlaylistItem.objects.filter(data__snippet__playlistId = playlistId)
        if not items:
            print("Playlist「%s」" % (self,len(items)))
            sys.exit()
        return list(items)
    
    def download_playlistItems(self):
        playlistItems = []
        pageToken = ""
        print("プレイリスト「%s」のプレイリストアイテムをダウンロード" % self)
        while True:
            res = youtube_with_key.playlistItems().list(
                playlistId = self.playlistId(),
                part='snippet',
                maxResults = 100,
                pageToken = pageToken
            ).execute()
            playlistItems.extend(res["items"])
            try:
                pageToken = res["nextPageToken"]
                continue
            except:
                break
        for data in playlistItems:
            PlaylistItem.objects.create(data = data)
    
    def update(self):
        response = youtube_with_auth.playlists().update(
            part="snippet,status",
            body=self.data
        ).execute()
        print("プレイリスト「%s」が更新されました" % response["snippet"]["title"])
        self.data = response
        self.save()

    def rewrite_title(self):
        title = self.title()
        data = self.data
        data["snippet"]["title"] = title
        self.data = data

    def type_name(self):
        s = re.findall("\s(.*?)\d",self.title())
        if not s:return "他"
        type_name = s[0]
        if not type_name in [choice[0] for choice in VIDEO_TYPE_CHOICES]:return "他"
        return type_name
    
    def genre_name(self):
        s = re.findall("(.*?)\s",self.title())
        if not s : return "他"
        return s[0]
    
class PlaylistItem(models.Model):
    data = models.JSONField(help_text='このFieldはYoutubeAPIによって読み込まれます。')

    def title(self):
        return self.data["snippet"]["title"]
    
    def videoId(self):
        return self.data["snippet"]['resourceId']["videoId"]
    
    def playlistId(self):
        return self.data["snippet"]["playlistId"]
    
    def __str__(self):
        return self.title()
    
    def download_video(self):
        print("プレイリストアイテム「%s」のビデオをダウンロード" % self)
        res = youtube_with_key.videos().list(
            id = self.videoId(),
            part='snippet',
        ).execute()
        new_data = res["items"][0]
        try:
            old_video = Video.objects.get(data__id = new_data["id"])
            old_video.data = new_data
            old_video.save()
            print("Video「%s」のデータを更新しました" % old_video)
            return old_video
        except:
            new_video = Video.objects.create(data = new_data)
            print("Video「%s」を新たに追加しました。" % new_video)
            return 
        
    def video(self):
        try:
            return Video.objects.get(data__id = self.videoId())
        except:
            videos = Video.objects.filter(data__id = self.videoId())
            if len(videos)==0:
                print("Video「%s」は存在しません！" % self)
                if input("ダウンロードしますか？y/n")=="n": return
                return self.download_video()
            if len(videos)>1:
                print("Video「%s」は複数存在します！" % self)
                if input("ダウンロードしなおしますか？y/n")=="n": return
                videos.delete()
                return self.download_video()
            
        # print("Video「%s」を取得" % videos[0])
        

class Video(models.Model):
    data = models.JSONField(help_text='このFieldはYoutubeAPIによって読み込まれます。')
    new_data = models.JSONField(null=True,blank = True,help_text='補正後のデータです。')

    class Meta:
        ordering = ['-id']

    def videoId(self):
        return self.data["id"]
    
    def title(self):
        return self.data["snippet"]["title"]
    
    def set_title(self,title:str):
        self.new_data = self.data
        self.new_data["snippet"]["title"] = title
        return self
    
    def title_in_mytex(self):
        text = text_transform.line_to_tex(self.title())
        text = text.replace("$ ","$").replace(" $","$")
        return text
    
    def description(self):
        return self.data["snippet"]["description"]
    
    def set_description(self,text):
        self.new_data = self.data
        self.new_data["snippet"]["description"] = text
        return self
    

ugosite/views.py
# from types import NoneType
from django.shortcuts import render

import youtube.views

# Create your views here.

# ここからがUgosuu

from .models import MyFile,Category, Article, Source, Term,  Problem
from django.contrib.auth.models import User #Blog author or author
from django.views import generic

from django.shortcuts import get_object_or_404

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.urls import reverse


from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect


from django.views.generic import TemplateView

import os 

import re


import pprint



from googletrans import Translator
tr = Translator()
tr.raise_Exception = True

import urllib.parse as parse

def index(request):
    """View function for home page of site."""
    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_categorys' : Category.objects.all().count(),
        'num_articles': Article.objects.all().count(),
        'num_problems' : Problem.objects.all().count(),
        'num_problems_of_univ' : Problem.objects.filter(source__isnull = False).count(),
        'num_terms': Term.objects.all().count(),
        'num_visits': num_visits,
        'article_list' : Article.objects.all()[:3],
        'category_list' : Category.objects.filter(parent__isnull=True),
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


class ArticleDetailView(generic.DetailView):
    model = Article
    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView,self).get_context_data(**kwargs)
        url = "articles/"+self.kwargs['id']+".html"
        context['template'] = os.path.isfile("ugosite/templates/"+url)
        context['html'] = url
        article = context["article"]
        if article.categorys.all():
            category = article.categorys.all()[0]
            articles = Article.objects.filter(parent = category)
            index = list(articles).index(article)
            if not len(articles) == index+1:
                context['next'] = articles[index+1].get_absolute_url()
            if not index-1<0:
                context['prev'] = articles[index-1].get_absolute_url()
            context['up'] = category.get_absolute_url()
        context['ancestors'] = article.ancestors()
        context['category'] = article.category
        context['self'] = article
        return context

class ArticleListView(generic.ListView):
    model = Article
    paginate_by = 500


class TermDetailView(generic.DetailView):
    model = Term


class TermListView(generic.ListView):
    model = Term
    paginate_by = 500


class CategoryDetailView(generic.DetailView):
    model = Category
    def get_context_data(self, **kwargs):
        context = super(CategoryDetailView,self).get_context_data(**kwargs)
        context["categorys"] = [context["category"]]
        return context

class CategoryListView(generic.ListView):
    model = Category
    def get_context_data(self, **kwargs):
        context = super(CategoryListView,self).get_context_data(**kwargs)
        context["category_list"] = Category.objects.filter(parent__isnull = True)
        context["article_list"] = Article.objects.all()
        return context


class ProblemDetailView(generic.DetailView):
    def get_context_data(self, **kwargs):
        context = super(ProblemDetailView,self).get_context_data(**kwargs)
        problem = context["problem"]
        category = problem.categorys.all()[0]
        context["category"] = category
        problems = Problem.objects.filter(categorys = category) 
        index = list(problems).index(problem)
        if not len(problems) == index+1:
            context['next'] = problems[index+1].get_absolute_url()
        if not index-1<0:
            context['prev'] = problems[index-1].get_absolute_url()
        context['up'] = problem.get_absolute_url()
        context['ancestors'] =  category.ancestors()+[category]
        context['self'] = problem
        return context
    model = Problem

class ProblemListView(generic.ListView):
    model = Problem
    paginate_by = 100

import certifi
certifi.where()

from youtube.models import ChannelSection,Playlist

from .models import QuestionSet

class ArticleGenerater:
    # def make_from_playlist(self):
    def test(self):
        sections = ChannelSection.objects.filter(data__snippet__type = "multipleplaylists")
        for k,section in enumerate(sections):
            print("\n\n%s:%s" % (k+1,section))
            playlists = section.playlists()
            for i,playlist in enumerate(playlists):
                print(" %s:%s" % (i+1,playlist))
                playlistItems = playlist.playlistItems()
                for j,playlistItem in enumerate(playlistItems):
                    print("  %s:%s" % (j+1,playlistItem))
                    video = playlistItem.video()

    def make_from_playlists(self):
        for i,playlist in enumerate(Playlist.objects.all()):
            print(" %s:%s" % (i+1,playlist))
            QuestionSet().make_from_playlist(playlist)


# ArticleGenerater().test()

ugosite/templates/ancestors.html
<div class="ancestors">
    {% for a in ancestors %}
        <a href = "{{ a.get_absolute_url }}" >{{ a.name }}＞</a>
    {% endfor %}
    {{ self.name }}
</div>

ugosite/templates/article_detail.html
<h2>{{ article.name }}</h2>

<p>
{{ article.description | safe}}
</p>

<p>
{{ article.content | safe}}
</p>


{% if template %}
<div class ="tex">{% include html %}</div>
{% endif %}

{% comment %}

  {% if article.modules.first.genres.first.ancestors %}
  <p><strong>Genres:</strong> 
    {% for ancestor in article.modules.first.genres.first.ancestors %}
        <a href ="{{ ancestor.get_absolute_url }}">{{ ancestor.name }}＞</a>
    {% endfor %}
  </p>
  {% endif %}

  {% if article.terms.all %}
  <p><strong>Terms:</strong> 
    {% for term in article.terms.all %}
      <a href ="{{ term.get_absolute_url }}">{{ term.name }}</a>, 
    {% endfor %}
  </p>
  {% endif %}

{% endcomment %}

{% if article.problem_set.all %}
<ol class="problems">
  {% for problem in article.problem_set.all %}
  <li class="linkdiv problem" itemid="{{ problem.id }}">
    <a href ="#{{ problem.id }}">{{ problem.name }}</a>
    <div class="text tex">
      <a href = "{{ problem.video_set.first.get_absolute_url }}">{{ problem.text | safe }}</a>
    </div>
  </li>
  {% endfor %}
</ol>
{% endif %}

ugosite/templates/base_generic.html
<!DOCTYPE html>
<html lang="jp">
<head>
  {% block title %}<title>Ugosuu</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/page-links.css' %}">

  <!-- JSXgraph -->
  <link rel="stylesheet" type="text/css" href="https://jsxgraph.org/distrib/jsxgraph.css" />
  <script type="text/javascript" src="https://jsxgraph.org/distrib/jsxgraphcore.js"></script>

  <!-- MathJax -->
  <script>
    MathJax = {
      loader: {load: ['[tex]/html']},
      chtml: {
        displayAlign: "left",
        displayIndent: '50px',
      },
      tex: {
        inlineMath: [['$', '$'], ['\\(', '\\)']],
        // packages: {'[+]': ['html']}
        }
    };
  </script>
  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
</head>
<body>
  <header>
    {% block nav %}
    <div class="logo"><a href="{% url 'index' %}">Ugosuu</a></div>
    <div class="main-nav">
      <ul>
        <li><a href="{% url 'categorys' %}">カテゴリ</a></li>
        <li><a href="{% url 'problems' %}">問題</a></li>
        <li><a href="{% url 'video_search' '1' %}">動画検索</a></li>
        {% comment %} <li><a href="{% url 'random_video' %}">ランダム動画</a></li> {% endcomment %}
        <li><a href="{% url 'terms' %}">用語</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'logout'%}?next={{request.path}}">User</a>:</li>
        {% else %}
        <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
        {% endif %}
      </ul>
    </div>
    {% endblock %}
  </header>

  <nav class="subnav">
    {% block subnav %}
    
    {% endblock %}
  </nav>

  <main>
    <article>
      {% block content %}
      {% endblock %}
      {% block pagination %}
          {% if is_paginated %}
              <div class="pagination">
                  <span class="page-links">
                      {% if page_obj.has_previous %}
                          <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">◀︎</a>
                      {% else %}
                          <a>◁</a>
                      {% endif %}
                      <span class="page-current">
                          {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
                      </span>
                      {% if page_obj.has_next %}
                          <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">▶︎</a>
                      {% else %}
                        <a>▷</a>
                      {% endif %}
                  </span>
              </div>
          {% endif %}
      {% endblock %}
  </article>
  </main>
  
  <!-- <aside class="mokuji" id="mokuji">
    {% block rightbar %}
    {% endblock %}
  </aside> -->

  <nav class="listNav">
    <div id="folders">
      {% block folders %}
      {% endblock %}
    </div>
    <div class = "border">
    </div>
    <div id="files">
      {% block files %}
      {% endblock %}
    </div>
    <div class = "border">
    </div>
  </nav>

  <!-- <aside class="related">
    {% block related %}
    {% endblock %}
  </aside> -->

  <footer>
    <ul>
      <li  class = "linkdiv">
        <a href="#">
          Youtube
        </a>
      </li>
      <li  class = "linkdiv">
        <a href="#">
          Twitter
        </a>
      </li>
    </ul>
  </footer>
</body>

<script>
  if(document.querySelector(".player")){
      var tag = document.createElement('script');
      tag.src = "https://www.youtube.com/iframe_api";
      var firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
  }
  function add_video(slug,width){
      document.querySelector(".player").setAttribute("id","player")
      var player;
      player = new YT.Player('player',{
          height: width*9/16,
          width: width,
          videoId: slug,
      });
      var table
      table = document.querySelector(".table")
      if(table){
          for(let line of table.children){
                line.addEventListener("click",function(){
                const timeCord = line.textContent.match(/(?<min>[\d]+):(?<sec>[\d]+)/).groups
                console.log(timeCord)
                const time = Number(timeCord["min"])*60+Number(timeCord["sec"])
                console.log(time)
                player.seekTo(time, Boolean)
              })
            line.setAttribute("href",'javascript:void(0);')
          }
      }
  }
</script>

{% block scripts %}
{% endblock %}

</html>

ugosite/templates/category_system.html
<script defer>
    folderSystem()
    function folderSystem(){
        for(let folder of document.querySelectorAll("#folders .folder")){
            folder.querySelector(":scope>a").addEventListener("click",()=>selectFolder(folder)) 
        }
        function selectFolder(folder){
            folder.parentNode.querySelectorAll(".folder").forEach((f)=>f.classList.remove("selected"))
            folder.classList.add("selected")
            // pool(folder.cloneNode(true))
        }
        // const poollist = document.createElement("ul")
        // document.getElementById("files").appendChild(poollist)
        function pool(folder){
            while(poollist.firstChild){
                poollist.removeChild(poollist.firstChild)
            }
            document.getElementById("files").appendChild(folder)
            for(let file of folder.querySelectorAll(".file")){
                // poollist.appendChild(file)
                console.log("poollistに"+file+"を追加する")
                file.addEventListener("click",()=>selectFile(file))
            }
            function selectFile(file){
                    file.parentNode.querySelectorAll(".file").forEach((f)=>f.classList.remove("selected"))
                    file.classList.add("selected")
                    display(file.cloneNode(true))
                }
        }
        const detailDiv = document.getElementById("file-detail")
        function display(file){
            console.log(file+"をdetailに表示します")
            const detail = file.lastElementChild
            while(detailDiv.firstChild){
                detailDiv.removeChild(detailDiv.firstChild)
            }
            detailDiv.appendChild(detail)
            if(detailDiv.querySelector(".player")){
                width = detailDiv.clientWidth
                add_video(file.getAttribute("itemid"),width)
            }
        }

        
        
        //article内のproblemまで表示させるための関数
        document.querySelectorAll("#folders .file").forEach(
            (file)=>file.firstElementChild.addEventListener("click",()=>createTable(file))
        )
        function createTable(file){
            file.parentNode.querySelectorAll(".file").forEach((f)=>f.classList.remove("selected"))
            file.classList.add("selected")
            display(file.cloneNode(true))
            for(let problem of file.querySelectorAll(".problems .problem")){
                const itemid = problem.getAttribute("itemid")
                detailDiv.querySelector('.problem[itemid="'+itemid+'"]').setAttribute("id",itemid)
            }
        }

        // 閲覧項目のハイライト
        document.querySelector("main").addEventListener("scroll",function(){
            let nowTop = 1000000
            let disP
            if(detailDiv.querySelectorAll(".problem")){
                for(let problem of detailDiv.querySelectorAll(".problem")){
                    let top = problem.getBoundingClientRect().top
                    if(top>60 && top<nowTop){
                        nowTop = top
                        disP = problem
                        console.log("現在の表示問題は"+problem.querySelector("a").textContent+"です。")
                    } 
                }
                document.querySelectorAll(".problem").forEach((l)=>l.classList.remove("selected"))
                let id = disP.getAttribute("id")
                document.querySelectorAll('.problem[itemid="'+id+'"]').forEach((l)=>l.classList.add("selected"))
            }
        })
    }
</script>

ugosite/templates/categorys.html
<ul>
    {% for g in categorys %}
        {% if g.children %}
        <li class ="folder linkdiv" itemid="{{ g.id }}">
            <a href="#">
                {% if g.icon %}
                {{ g.icon | safe }} 
                {% endif %}
                {{ g.name }}
            </a>
            {% include "categorys.html" with categorys=g.category_set.all %}
            <ul>
                {% for p in g.article_set.all %}
                    <li class="file linkdiv" itemid="{{ p.id }}">
                        <a href="#">{{ p.name }}</a>
                        <div class="article-detail">
                            {% include "article_detail.html" with article=p%}
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </li>
        {% endif %}
    {% endfor %}
</ul>

ugosite/templates/next-prev.html
<div class="next-prev">
    {% if prev %}
        <a href="{{ prev }}">prev</a>
    {% else %}
        <a>prev</a>
    {% endif %}
    |
    {% if up %}
        <a href="{{ up }}">up </a>
    {% else %}
        <a>up</a>
    {% endif %}
    |
    {% if next %}
        <a href="{{ next }}">next</a>
    {% else %}
      <a>next</a>
    {% endif %}
  </div>

ugosite/templates/problem_detail.html
  <h2>{{ problem.name }}</h2>

  <!-- <h3>問題</h3> -->
  {% if problem.source %}
    <p class = "source">{{ problem.source | safe }}</p>
  {% endif %}
    <p class = "tex"> {{ problem.text | safe }}</p>
  
  {% if problem.answer %}
  <details><summary><strong>解答例</strong></summary>
      <p class = "tex">{{ problem.answer | safe }}</p>
  {% endif %}

  {% if problem.video_set.first %}
  <details><summary><strong>解説動画</strong></summary>
    {% include "youtube-embedding.html" with video=problem.video_set.first %}
  </details>
  {% endif %}

  {% if problem.article_set.all %}
  <p><strong>Articles:</strong> 
    {% for article in problem.article_set.all  %}
      <a href="{{ article.get_absolute_url }}">{{ article.name }}</a>，
    {% endfor %}
  </p>
  {% endif %}

　<a href = "{{ problem.get_admin_url }}">[adminで編集]</a>